include:
  - project: "WOG/GVT/ship/ship-hats-templates"
    ref: "main"
    file:
      # Direct link https://sgts.gitlab-dedicated.com/wog/gvt/ship/ship-hats-templates/-/blob/main/templates/.gitlab-ci-common.yml
      - /templates/.gitlab-ci-common.yml

build-docker-image:
  stage: build
  extends: .run-docker-in-docker
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    # fetches the latest image (not failing if image is not found)
    - docker pull $IMAGE_TAG || true
    - docker build -t $IMAGE_TAG --build-arg DOCKER_VERSION=$DOCKER_VERSION --file Dockerfile .
    - docker push $IMAGE_TAG
