# Refer to: How to Manage GitLab Runner Concurrency For Parallel CI Jobs
# https://www.howtogeek.com/devops/how-to-manage-gitlab-runner-concurrency-for-parallel-ci-jobs/
concurrent = ${RUNNER_CONCURRENCY}
check_interval = 0

[session_server]
 session_timeout = 1800

# Runners (to be added at runtime based on MANAGERS_CONFIGS)
