LogLevel = "info" 
LogFormat = "text" 
 
[Fargate] 
 Cluster = "${FARGATE_CLUSTER}"
 Region = "${FARGATE_REGION}"
 Subnet = "${FARGATE_SUBNET}"
 SecurityGroup = "${FARGATE_SECURITY_GROUP}"
 TaskDefinition = "${FARGATE_TASK_DEFINITION}"
 EnablePublicIP = false
 
[TaskMetadata] 
 Directory = "/opt/gitlab-runner/metadata" 
 
[SSH] 
 Username = "root" 
 Port = 22
